
name: Wipe Repository

on:
  workflow_dispatch: 

jobs:
  wipe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Remove all files
        run: |
          shopt -s extglob
          rm -rf !(.git|.github)

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "Wipe repository contents" || echo "Nothing to commit"
          git push
